apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chaoscraft-control-plane.fullname" . }}-db
  labels:
    {{- include "chaoscraft-control-plane.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  database-url: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "chaoscraft-control-plane.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}?sslmode=disable"
  {{- else }}
  database-url: "postgres://{{ .Values.externalDatabase.username }}:{{ .Values.externalDatabase.password }}@{{ .Values.externalDatabase.host }}:{{ .Values.externalDatabase.port }}/{{ .Values.externalDatabase.database }}?sslmode=disable"
  {{- end }}
