apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chaoscraft-control-plane.serviceAccountName" . }}
  labels:
    {{- include "chaoscraft-control-plane.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
